clc;
workspace;
close all;
training_data = {   'inputs/zero_to_nine_Mayur1.wav', ...
            'inputs/zero_to_nine_Mayur2.wav', ...
            'inputs/zero_to_nine_Shrikant1.wav', ...
            'inputs/zero_to_nine_Shrikant2.wav', ...
            'inputs/zero_to_nine_Vedhas1.wav', ...
            'inputs/zero_to_nine_Vedhas2.wav', ...
            'inputs/zero_to_nine_Niramay1.wav', ...
            'inputs/zero_to_nine_Niramay2.wav', ...
            'inputs/zero_to_nine_divyansh1.wav', ...
            'inputs/zero_to_nine_divyansh2.wav', ...
            'inputs/zero_to_nine_Jatin1.wav', ...
            'inputs/zero_to_nine_Jatin2.wav', ...
            'inputs/zero_to_nine_Hitesh1.wav', ...
            'inputs/zero_to_nine_Hitesh2.wav', ...
            'inputs/zero_to_nine_Kaustuv1.wav', ...
            'inputs/zero_to_nine_Kaustuv2.wav', ...
            'inputs/zero_to_nine_Ankita1.wav', ...
            'inputs/zero_to_nine_Ankita2.wav', ...
            'inputs/zero_to_nine_Mansi1.wav', ...
            'inputs/zero_to_nine_Mansi2.wav', ...
            'inputs/zero_to_nine_Kamini1.wav', ...
            'inputs/zero_to_nine_Kamini2.wav', ...
            'inputs/zero_to_nine_Pragya1.wav', ...
            'inputs/zero_to_nine_Pragya2.wav', ...
            'inputs/zero_to_nine_Prarthana1.wav', ...
            'inputs/zero_to_nine_Prarthana2.wav', ...
            'inputs/zero_to_nine_Reshma1.wav', ...
            'inputs/zero_to_nine_Reshma2.wav', ...
            'inputs/zero_to_nine_Richa1.wav', ...
            'inputs/zero_to_nine_Richa2.wav', ...
            'inputs/zero_to_nine_Shradha1.wav', ...
            'inputs/zero_to_nine_Shradha2.wav'
            
         };

file_no = 16;
winlen = 4001; %for calculating short-time energy 
overlap1 = 1000;%due to conv digit length increases,overlap1 is deducted
overlap2 = 1200;%due to conv digit length increases,overlap2 is deducted
threshold = 0.2;  
filename = training_data{file_no};
[data_inp, fSampling] = audioread(filename);

%%pre-emphesis 
data_inp = data_inp - 0.95 * [0; data_inp(1:size(data_inp,1)-1)];

%energy calculation
energy = data_inp .^ 2;
summ = ones(1, winlen);
energy = conv(energy, summ);

ptr = 1;
for k=0:9
    k;
    while energy(ptr) < threshold
        ptr = ptr + 1;
    end
    first = ptr;
    while energy(ptr) >= threshold
        ptr = ptr + 1;
    end
    last = ptr;
    digit_data = data_inp(max(1, first - overlap1):min(last-overlap2, size(data_inp, 1)));
    audiowrite(strcat(filename(21:end-4), num2str(k), '0.wav'), digit_data, fSampling);

    while energy(ptr) < threshold
        ptr = ptr + 1;
    end
    first = ptr;
    while energy(ptr) >= threshold
        ptr = ptr + 1;
    end
    last = ptr;
    digit_data = data_inp(max(1, first - overlap1):min(last-overlap2, size(data_inp, 1)));
    audiowrite(strcat(filename(21:end-4), num2str(k), '1.wav'), digit_data, fSampling);

end
disp(training_data{file_no});
